# Generated by Django 5.1.6 on 2025-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='item name')),
                ('description', models.CharField(default='Hello', max_length=200, verbose_name='item description')),
                ('price', models.IntegerField(verbose_name='item price')),
            ],
        ),
    ]
