# Generated by Django 5.1.6 on 2025-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/027/277/492/non_2x/eat-healthy-icon-in-illustration-vector.jpg', max_length=500),
        ),
    ]
